language: python
python:
    - "3.4"
before_install:
  - sudo apt-get install -y graphviz
  - sudo python3 -m pip install graphviz
install:
    - pip install .
condition: $TRAVIS_PYTHON_VERSION = "3.4"
